CREATE TABLE IF NOT EXISTS TEST (
	TID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TNAME VARCHAR(55) NOT NULL
);

CREATE TABLE IF NOT EXISTS TEST2 (
	TID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TNAME VARCHAR(55) NOT NULL
);
